# Generated by Django 4.0 on 2022-03-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='profit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='sp_price',
            field=models.IntegerField(default=0),
        ),
    ]
