# Generated by Django 4.0 on 2022-03-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_profit_sale_sp_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='type',
            field=models.CharField(choices=[('Kg', 'Kgs'), ('Tonnes', 'Tonnes'), ('lts', 'Litres')], max_length=20),
        ),
    ]
