# Generated by Django 4.0 on 2022-03-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='bp_price',
            field=models.CharField(default='000', max_length=20),
            preserve_default=False,
        ),
    ]
