# Generated by Django 4.0 on 2022-03-14 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_bp_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='type',
        ),
    ]
