# Generated by Django 4.0 on 2022-03-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bp_price',
            field=models.IntegerField(default=0),
        ),
    ]
