# Generated by Django 4.0 on 2022-03-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_bp_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Kg', 'Kgs'), ('Tonnes', 'Tonnes'), ('lts', 'Litres')], max_length=20),
        ),
    ]
