# Generated by Django 4.0 on 2022-03-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Kg', 'Kgs'), ('Tonnes', 'Tonnes'), ('lts', 'Litres'), ('number', 'Number')], max_length=20),
        ),
    ]
